### ISSUE TITLE
Error with apiscrip.js

### ISSUE THREAD

**Issue by Newtim** [jfflbnntt/roll20-api-scripts#4]
Hello I am getting the following error when trying to use bubble script.  afraid I don't know how to fix.

API Output Console

Your scripts are currently disabled due to an error that was detected. Please make appropriate changes to your scripts and click the "Save Script" button and we'll attempt to start running them again. More info...

For reference, the error message generated was: TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at comp.>=._.each._.every._.some._.some.fixNewObject (apiscript.js:10845:22)
    at comp.>=._.each._.every._.some._.some.findOrCreateBubbleParts (apiscript.js:10807:28)
    at comp.>=._.each._.every._.some._.some.speechBalloon (apiscript.js:10874:27)
    at comp.>=._.each._.every._.some._.some.checkBubbleDisplay [as _repeat] (apiscript.js:10780:13)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by jfflbnntt** [comment]
Thanks for the report. Seems maybe something in the api has changed. I'll have to look into it.

**Comment by Newtim** [comment]
Thank you for your help, I am just a beginner coder, so I am not much help.  Please let me know if I can help with anything and appreciate your work.  I think this would be awesome for my Marvel campaign.

**Comment by jfflbnntt** [comment]
@Newtim Seems to work now without throwing the error. Let me know if you see anything else going on with the script.
